#+title: Divórcio e o Regulamento Bruxelas II /ter/
#+author: João Gomes de Almeida
#+options: toc:nil
#+cite_export: csl chicago.csl

* I. Introdução
A generalidade das normas do Regulamento Bruxelas II /ter/ serão aplicáveis a partir do dia 1 de agosto de 2022[fn:1]. Este Regulamento reformula e substitui o Regulamento Bruxelas II /bis/[fn:2], porventura o regulamento mais relevante em matéria de Direito Internacional Privado da família. Neste artigo, analisa-se o Regulamento Bruxelas II /ter/ procurando determinar quais as novidades introduzidas em matéria matrimonial, tomando por referência o divórcio transnacional. Atendendo a que, em matéria matrimonial, estamos perante um regulamento dupla, que estabelece regras de competência internacional e de reconhecimento, analisar-se-ão cada uma destas em secção autónoma (II. e III.), para depois se apresentarem as conclusões (IV.)


* II. Competência internacional
* III. Reconhecimento
* IV. Conclusões

* Footnotes
[fn:2] Regulamento (CE) n.º 2201/2003 do Conselho, de 27 de Novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.º 1347/2000, publicado no JO L 338, de 23 de dezembro de 2003.

[fn:1] Regulamento (UE) 2019/1111 do Conselho, de 25 de junho de 2019, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e ao rapto internacional de crianças (reformulação), publicado no Jornal Oficial (JO) L 178, de 2 de julho de 2019.
