#+title: Divórcio e o Regulamento Bruxelas II /ter/
#+author: João Gomes de Almeida
#+options: toc:nil
#+cite_export: csl chicago.csl

* I. Introdução
A generalidade das normas do Regulamento Bruxelas II /ter/ serão aplicáveis a partir do dia 1 de agosto de 2022[fn:1]. Este Regulamento reformula e substitui o Regulamento Bruxelas II /bis/[fn:2], porventura o regulamento mais relevante em matéria de Direito Internacional Privado da família. Neste artigo, analisa-se o Regulamento Bruxelas II /ter/ procurando determinar quais as novidades introduzidas em matéria matrimonial, tomando por referência o divórcio transnacional. O foco do presente estudo é, pois, no apuramento de quais as novidades e não numa análise detalhada de todas as regras em matéria matrimonial do Regulamento Bruxelas II /ter/, em especial daquelas que se mantêm substancialmente inalteradas face ao Regulamento Bruxelas II /bis/[cite:para uma análise detalhada das regras do Regulamento Bruxelas II /bis/, cf.; @almeida2017;@mendes2022 pp. xx e ss.;@mendes2022a pp. xx e ss.;no Regulamento Bruxelas II /ter/, cf. @almeida2022a;@oliveira2022;e @almeida2022; ]. Ainda assim, procurar-se-á dar nota de desenvolvimentos recentes, sobretudo ao nível da jurisprudência do Tribunal de Justiça da União Europeia. Inicia-se a análise pelo âmbito de aplicação e definições (II.) do Regulamento Bruxelas II /ter/, prosseguindo depois, atendendo a que, em matéria matrimonial, estamos perante um regulamento duplo, pelas regras de competência internacional (III.) e de reconhecimento (IV.), apresentando no final as conclusões (V.)

* II. Âmbito de aplicação e definições
/Em razão do espaço/, as normas do Regulamento Bruxelas II /ter/ só são aplicáveis quando a situação tenha um elemento de estraneidade[cite:Cf., por todos; @musseva2022, p. 20]. Este entendimento - que não tinha uma consagração clara no Regulamento Bruxelas II /bis/[cite:Sobre a questão neste Regulamento, cf.;@almeida2017, pp. 71 e ss.] - pode encontrar-se hoje nos considerandos 2 a 4 do Regulamento Bruxelas II /ter/ e é o único conforme ao artigo 81.º, n.º 3, do Tratado sobre o Funcionamento da União Europeia (doravante TFUE), base habilitante do Regulamento Bruxelas II /ter/, no qual se estabelece que as medidas relativas à família devem ter "incidência transfronteiriça".

Assinala-se, quanto às normas de reconhecimento em matéria matrimonial, que o elemento de estraneidade pode surgir /depois/ de proferida a decisão, exarado o ato autêntico ou celebrado o acordo. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês, na sequência de ação instaurada em setembro de 2022. Posteriormente, B. muda a sua residência habitual para Portugal e, em setembro de 2026, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

/Em razão do território/, não há novidades: tal como o Regulamento que o precedeu, o Regulamento Bruxelas II /ter/ é obrigatório e diretamente aplicável em todos os Estados-Membros, com exceção da Dinamarca[cite:Cf. @musseva2022 p. 19;@pinheiro2022 p.10;e @almeida2022a p. 12-13].

/Em razão do tempo/, o Regulamento entrou em vigor no dia 22 de julho de 2019 e as suas normas são aplicáveis a partir de 1 de agosto de 2022, com exceção dos artigos 92.º, 93.º e 103.º, que são aplicáveis a partir de 22 de julho de 2019[fn:3]. Como se depreende do artigo 100.º, n.º 1, o âmbito de aplicação em razão do tempo do Regulamento Bruxelas II /ter/ estará preenchido quando a ação seja instaurada[cite:Sobre a determinação do momento em que foi instaurado o processo cf.;@oliveira2022 pp.40-41;e, em sede de Regulamento Bruxelas II /bis/, @almeida2017 pp. 215 e ss.], o ato autêntico seja exarado ou o acordo seja registado a partir de 1 de agosto de 2022. Assim, e por exemplo, se, no dia 10 de outubro de 2022, é pedido em Portugal o reconhecimento de uma decisão espanhola de divórcio proferida no dia 1 de setembro de 2022, na sequência de processo instaurado em 20 de julho de 2022, não serão aplicáveis as regras de reconhecimento do Regulamento Bruxelas II /ter/, mas sim as do Regulamento Bruxelas II /bis/, como resulta do artigo 100.º, n.º 2, do Regulamento Bruxelas II /ter/[fn:4].

/Em razão da matéria/, o Regulamento Bruxelas II /ter/ abrange, em matéria civil, as ações matrimoniais (divórcio, separação e anulação do casamento). O conceito de matéria civil /não/ se encontra definido, embora se encontrem algumas pistas interpretativas e uma remissão para a jurisprudência do TJ nos considerandos n.ºs 4 e 5. A questão é  relevante em matéria matrimonial pois permite excluir do âmbito de aplicação as ações matrimoniais proferidas em processo de natureza meramente religiosa[cite:cf., neste sentido;@borras1998 p. 35, ponto 20;no qual se pode ler que "a menção do termo «cíveis» pretende delimitar claramente o objeto próprio da convenção. Com efeito, a menção não deve ser entendida unicamente em relação com os processos de carácter administrativo a que se refere o n.º 2 do mesmo artigo, mas sim que serve para excluir os processos de natureza meramente religiosa".].

O conceito de casamento também não se encontra definido, existindo sensíveis diferenças no modo como o Direito interno dos vários Estados-Membros define este conceito. Numa primeira aproximação, a utilização do conceito "casamento" permite concluir que o Regulamento Bruxelas II /ter/ não abrange relações de facto ou parcerias registadas[cite:Sobre a exclusão destas últimas, cf., com mais detalhes;@almeida2017 pp. 47 e ss.]. Apesar de não se encontrar definido, sustenta-se que deve ser feita uma interpretação autónoma do mesmo[cite:Cf., em sede de Regulamento Bruxelas II /bis/; @almeida2017 pp. 40 e ss.] Entende-se que o conceito de casamento perfilhado no Regulamento Bruxelas II /ter/ /abrange/ os casamentos de pessoas do mesmo sexo. O argumento literal que depunha em sentido contrário no Regulamento Bruxelas II /bis/ foi eliminado: nos formulários utiliza-se agora a expressão "cônjuge", neutra em termos de género[fn:5], quando antes se utilizavam as expressões "esposo" e "esposa"[fn:6]. E, na União Europeia, é atualmente difícil afirmar que não existe uma forte tendência no sentido de alargar o conceito de casamento às uniões entre pessoas do mesmo sexo.

Acompanhando um processo de "desjudicialização" do divórcio na União Europeia, o Regulamento Bruxelas II /ter/ admite o reconhecimento de atos autênticos e acordos em matéria de divórcio e separação judicial[fn:7]. O âmbito de aplicação material do Regulamento Bruxelas II /ter/ abrange assim divórcios /privados/, definidos por alguma doutrina como aqueles em que não há uma intervenção /constitutiva/ de uma autoridade[cite:Cf., neste sentido; @gonzalezbeilfuss2020 p.312;@gonzalezbeilfuss2021a p. 97;e @kramme2021 p. 101;@lazic2021 pp.165-166, parecem preferir distinguir os divórcios privados pelo documento em que são vertidos ou registados.]. Preferimos distinguir recorrendo ao conceito de autoridade. No âmbito de aplicação material do Regulamento Bruxelas II /ter/ incluem-se agora, adicionalmente, divórcios e separações judiciais em que há uma intervenção de uma autoridade (seja ela constitutiva ou não); os divórcios /puramente/ privados, isto é, os divórcios efetuados sem necessidade da presença de qualquer autoridade, continuam excluídos do âmbito de aplicação material do Regulamento.

/Quanto às definições/, o Tribunal de Justiça tem assinalado que os conceitos usados nos regulamentos e em outros diplomas da União Europeia devem ser objeto de interpretação autónoma[fn:8] relativamente ao Direito dos Estados-Membros e vincado que a interpretação dos atos da União Europeia deve ter em conta o contexto da disposição e o objetivo prosseguido pela regulamentação em causa[cite:Na doutrina portuguesa, cf.;@pinheiro2014 pp. 460-461;em sede do Regulamento Roma II @oliveira2011 pp. 213 e ss.;e @almeida2017 pp. 34-35 e 114-119.]. A esta luz, as definições constantes do artigo 2.º têm particular relevância pois promovem uma interpretação e aplicação /uniforme/ das regras do Regulamento Bruxelas II /ter/ nos vários Estados-Membros. Em matéria matrimonial, as novas definições incidem apenas sobre as normas de reconhecimento, pelo que serão abordadas /infra/ em IV.

Merece uma nota o artigo 2.º, n.º 3, do Regulamento Bruxelas II /ter/, que introduz uma novidade /ao nível da técnica legislativa/, ainda que não de substância. Neste preceito estabelece-se que para efeitos dos artigos 3.º, 6.º, 10.º, 12.º, 13.º, 51.º, 59.º, 75.º, 94.º e 102.º o conceito de «domicílio» substitui o conceito de «nacionalidade» para a Irlanda e o Reino Unido e tem o mesmo significado que nos respetivos ordenamentos jurídicos desses Estados-Membros[cite:Sobre este conceito, cf., com maiores detalhes;@almeida2017 pp. 142 e ss. e bibliografia aí indicada.]. Trata-se de uma concessão efetuada a estes Estados-Membros que constava já dos intrumentos precedentes. No Regulamento Bruxelas II /ter/ verifica-se uma alteração de técnica legislativa: ao invés de prever a substituição em cada um dos artigos em que ela é necessária, efetua-se a mesma numa única disposição que indica os artigos em que a substituição deve ocorrer. Atualmente, a substituição releva apenas para a Irlanda, pois o Reino Unido deixou, por via do /Brexit/, de ser um Estado-Membro. Tal significa, desde logo, que a substituição deixa de ser necessária no artigo 102.º, uma vez que a Irlanda não é um ordenamento jurídico complexo. Não se vê, igualmente, que seja necessário efetuar qualquer substituição no artigo 94.º, uma vez que ele não se refere ao elemento de conexão nacionalidade, mas sim ao princípio da não discriminação em razão da nacionalidade. Os restantes artigos ou correspondem a anteriores preceitos que já previam a substituição em sede do Regulamento Bruxelas II /bis/[fn:9] ou a artigos novos que recorrem à nacionalidade[fn:10].

Da perspetiva dos tribunais portugueses a questão pode parecer irrelevante, pois não vão, por exemplo, aferir a sua competência internacional através do recurso ao conceito de "domicílio". Todavia a apreensão deste conceito pelos tribunais portugueses é relevante para efeitos do artigo 6.º do Regulamento Bruxelas II /ter/: se dois cônjuges têm "domicílio" na Irlanda, os tribunais portugueses não podem recorrer às normas atributivas de competência internacional de fonte interna, porque os tribunais de um outro Estado-Membro (Irlanda) são competentes segundo as regras do Regulamento[fn:11]; é igualmente vedado o recurso às normas atributivas de competência internacional de fonte interna nos casos em que o cônjuge requerido tenha "domicílio" na Irlanda[fn:12].

* III. Competência internacional
* IV. Reconhecimento
* V. Conclusões

* Footnotes

[fn:12] Cf. artigo 2.º, n.º 3, e 6.º, n.º 2, do Regulamento Bruxelas II /ter/.

[fn:11] Os artigos 2.º, n.º 3, e 3.º, alínea /b)/, do Regulamento Bruxelas II /ter/ conferem competência internacional aos tribunais da Irlanda. O artigo 6.º, n.º 1, impede o recurso às normas de competência internacional de fonte interna.

[fn:10] Artigos 10.º, 12.º, 13.º, 51.º e 59.º.

[fn:9] Artigos 3.º, 6.º e 75.º.

[fn:8] A questão surgiu, inicialmente, com a interpretação dos conceitos da Convenção de Bruxelas de 1968 relativa à Competência Jurisdicional e à Execução de Decisões em Matéria Civil e Comercial, com maior acuidade no Acórdão de 14 de outubro de 1976, /Eurocontrol/, 29/76, EU:C:1976:137, considerando n.º 3. No âmbito do Regulamento Bruxelas II /bis/, veja-se, por exemplo, o Acórdão de 2 de abril de 2009, /A./, C-523/07, EU:C:2009:225, considerando n.º 34, e os recentes Acórdãos de 2 de agosto de 2021, /A. contra B./, proc. C-262/21 PPU, EU:C:2021:640, considerando n.º 40 e de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos n.º 38 e ss..

[fn:7] Cf. artigos 64.º e ss. do Regulamento Bruxelas II /ter/.

[fn:6] Cf. Anexo I do Regulamento Bruxelas II /bis/.

[fn:5] Cf. ponto 5.1 do Anexo II e ponto 6.1 do Anexo VII do Regulamento Bruxelas II /ter/.

[fn:4] O âmbito de aplicação em razão do tempo deve, assim, ser também articulado com a norma revogatória prevista no artigo 104.º do Regulamento Bruxelas II /ter/. Apesar de o Regulamento Bruxelas II /ter/ revogar o Regulamento Bruxelas II /bis/ com efeitos a partir de 1 de agosto de 2022 (artigo 104.º, n.º 1), as normas deste último Regulamento continuam a aplicar-se sempre que a ação tenha sido instaurada, o ato autêntico exarado e o acordo registado antes de 1 de agosto de 2022.

[fn:3] A data de produção de efeitos destes três artigos coincide com a data de entrada em vigor. Tal justifica-se por razões diversas: os artigos 92.º e 93.º atribuem à Comissão Europeia o poder de adotar atos delegados no que respeita aos anexos do Regulamento, podendo haver interesse em que a Comissão Europeia possa exercer este poder ainda antes da data de aplicação do Regulamento; o artigo 103.º estabelece obrigações de informação aos Estados-Membros, relacionadas com a operacionalização do Regulamento, que deveriam ser comunicadas à Comissão Europeia até 23 de abril de 2021.

[fn:2] Regulamento (CE) n.º 2201/2003 do Conselho, de 27 de Novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.º 1347/2000, publicado no JO L 338, de 23 de dezembro de 2003.

[fn:1] Regulamento (UE) 2019/1111 do Conselho, de 25 de junho de 2019, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e ao rapto internacional de crianças (reformulação), publicado no Jornal Oficial (JO) L 178, de 2 de julho de 2019.
