#+title: Divórcio e o Regulamento Bruxelas II /ter/
#+author: João Gomes de Almeida
#+options: toc:nil
#+cite_export: csl chicago.csl

* I. Introdução
A generalidade das normas do Regulamento Bruxelas II /ter/ serão aplicáveis a partir do dia 1 de agosto de 2022[fn:1]. Este Regulamento reformula e substitui o Regulamento Bruxelas II /bis/[fn:2], porventura o regulamento mais relevante em matéria de Direito Internacional Privado da família. Neste artigo, analisa-se o Regulamento Bruxelas II /ter/ procurando determinar quais as novidades introduzidas em matéria matrimonial, tomando por referência o divórcio transnacional. O foco do presente estudo é, pois, no apuramento de quais as novidades e não numa análise detalhada de todas as regras em matéria matrimonial do Regulamento Bruxelas II /ter/, em especial daquelas que se mantêm substancialmente inalteradas face ao Regulamento Bruxelas II /bis/[cite:Para uma análise detalhada das regras do Regulamento Bruxelas II /bis/, cf.; @almeida2017; @pinheiro2019c pp. *xx* e ss.; @pinheiro2019b pp. *xx* e ss.; @mendes2022 pp. *xx* e ss.; @mendes2022a pp. *xx* e ss.; no Regulamento Bruxelas II /ter/, cf. @almeida2022a; @oliveira2022; e @almeida2022]. Ainda assim, procurar-se-á dar nota de desenvolvimentos recentes, sobretudo ao nível da jurisprudência do Tribunal de Justiça da União Europeia. Inicia-se a análise pelo âmbito de aplicação e definições (II.) do Regulamento Bruxelas II /ter/, prosseguindo depois, atendendo a que, em matéria matrimonial, estamos perante um regulamento duplo, pelas regras de competência internacional (III.) e de reconhecimento (IV.), apresentando no final as conclusões (V.).

* II. Âmbito de aplicação e definições
/Em razão do espaço/, as normas do Regulamento Bruxelas II /ter/ só são aplicáveis quando a situação tenha um elemento de estraneidade[cite:Cf., por todos; @musseva2022, p. 20]. Este entendimento - que não tinha uma consagração clara no Regulamento Bruxelas II /bis/[cite:Sobre a questão neste Regulamento, cf.;@almeida2017, pp. 71 e ss.] - pode encontrar-se hoje nos considerandos 2 a 4 do Regulamento Bruxelas II /ter/ e é o único conforme ao artigo 81.º, n.º 3, do Tratado sobre o Funcionamento da União Europeia (doravante TFUE), base habilitante do Regulamento Bruxelas II /ter/, no qual se estabelece que as medidas relativas à família devem ter "incidência transfronteiriça".

Assinala-se, quanto às normas de reconhecimento em matéria matrimonial, que o elemento de estraneidade pode surgir /depois/ de proferida a decisão, exarado o ato autêntico ou celebrado o acordo. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês, na sequência de ação instaurada em setembro de 2022. Posteriormente, B. muda a sua residência habitual para Portugal e, em setembro de 2026, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

/Em razão do território/, não há novidades: tal como o Regulamento que o precedeu, o Regulamento Bruxelas II /ter/ é obrigatório e diretamente aplicável em todos os Estados-Membros, com exceção da Dinamarca[cite:Cf. @musseva2022 p. 19;@pinheiro2022 p.10;e @almeida2022a p. 12-13].

/Em razão do tempo/, o Regulamento entrou em vigor no dia 22 de julho de 2019 e as suas normas são aplicáveis a partir de 1 de agosto de 2022, com exceção dos artigos 92.º, 93.º e 103.º, que são aplicáveis a partir de 22 de julho de 2019[fn:3]. Como se depreende do artigo 100.º, n.º 1, o âmbito de aplicação em razão do tempo do Regulamento Bruxelas II /ter/ estará preenchido quando a ação seja instaurada[cite:Sobre a determinação do momento em que foi instaurado o processo cf.;@oliveira2022 pp.40-41;e, em sede de Regulamento Bruxelas II /bis/, @almeida2017 pp. 215 e ss.], o ato autêntico seja exarado ou o acordo seja registado a partir de 1 de agosto de 2022. Assim, e por exemplo, se, no dia 10 de outubro de 2022, é pedido em Portugal o reconhecimento de uma decisão espanhola de divórcio proferida no dia 1 de setembro de 2022, na sequência de processo instaurado em 20 de julho de 2022, não serão aplicáveis as regras de reconhecimento do Regulamento Bruxelas II /ter/, mas sim as do Regulamento Bruxelas II /bis/, como resulta do artigo 100.º, n.º 2, do Regulamento Bruxelas II /ter/[fn:4].

/Em razão da matéria/, o Regulamento Bruxelas II /ter/ abrange, em matéria civil, as ações matrimoniais (divórcio, separação e anulação do casamento). O conceito de matéria civil /não/ se encontra definido, embora se encontrem algumas pistas interpretativas e uma remissão para a jurisprudência do TJ nos considerandos n.ºs 4 e 5. A questão é  relevante em matéria matrimonial pois permite excluir do âmbito de aplicação as ações matrimoniais proferidas em processo de natureza meramente religiosa[cite:Neste sentido, cf.; @borras1998 p. 35, ponto 20, no qual se pode ler que "a menção do termo «cíveis» pretende delimitar claramente o objeto próprio da convenção. Com efeito, a menção não deve ser entendida unicamente em relação com os processos de carácter administrativo a que se refere o n.º 2 do mesmo artigo, mas sim que serve para excluir os processos de natureza meramente religiosa".].

O conceito de casamento também não se encontra definido, existindo sensíveis diferenças no modo como o Direito interno dos vários Estados-Membros define este conceito. Numa primeira aproximação, a utilização do conceito "casamento" permite concluir que o Regulamento Bruxelas II /ter/ não abrange relações de facto ou parcerias registadas[cite:Sobre a exclusão destas últimas, cf., com mais detalhes;@almeida2017 pp. 47 e ss.]. Apesar de não se encontrar definido, sustenta-se que deve ser feita uma interpretação autónoma do mesmo[cite:Cf., em sede de Regulamento Bruxelas II /bis/; @almeida2017 pp. 40 e ss.] Entende-se que o conceito de casamento perfilhado no Regulamento Bruxelas II /ter/ /abrange/ os casamentos de pessoas do mesmo sexo[cite:Cf., no mesmo sentido;@pinheiro2022 pp.5-6.]. O argumento literal que depunha em sentido contrário no Regulamento Bruxelas II /bis/ foi eliminado: nos formulários utiliza-se agora a expressão "cônjuge", neutra em termos de género[fn:5], quando antes se utilizavam as expressões "esposo" e "esposa"[fn:6]. E, na União Europeia, é atualmente difícil afirmar que não existe uma forte tendência no sentido de alargar o conceito de casamento às uniões entre pessoas do mesmo sexo.

Acompanhando um processo de "desjudicialização" do divórcio na União Europeia, o Regulamento Bruxelas II /ter/ admite o reconhecimento de atos autênticos e acordos em matéria de divórcio e separação judicial[fn:7]. O âmbito de aplicação material do Regulamento Bruxelas II /ter/ abrange assim divórcios /privados/, definidos por alguma doutrina como aqueles em que não há uma intervenção /constitutiva/ de uma autoridade[cite:Cf., neste sentido; @gonzalezbeilfuss2020 p.312;@gonzalezbeilfuss2021a p. 97;e @kramme2021 p. 101;@lazic2021 pp.165-166, parecem preferir distinguir os divórcios privados pelo documento em que são vertidos ou registados.]. Preferimos distinguir recorrendo ao conceito de autoridade. No âmbito de aplicação material do Regulamento Bruxelas II /ter/ incluem-se agora, adicionalmente, divórcios e separações judiciais em que há uma intervenção de uma autoridade (seja ela constitutiva ou não); os divórcios /puramente/ privados, isto é, os divórcios efetuados sem necessidade da presença de qualquer autoridade, continuam excluídos do âmbito de aplicação material do Regulamento.

/Quanto às definições/, o Tribunal de Justiça tem assinalado que os conceitos usados nos regulamentos e em outros diplomas da União Europeia devem ser objeto de interpretação autónoma[fn:8] relativamente ao Direito dos Estados-Membros e vincado que a interpretação dos atos da União Europeia deve ter em conta o contexto da disposição e o objetivo prosseguido pela regulamentação em causa[cite:Na doutrina portuguesa, cf.;@pinheiro2014 pp. 460-461;em sede do Regulamento Roma II @oliveira2011 pp. 213 e ss.;e @almeida2017 pp. 34-35 e 114-119.]. A esta luz, as definições constantes do artigo 2.º têm particular relevância pois promovem uma interpretação e aplicação /uniforme/ das regras do Regulamento Bruxelas II /ter/ nos vários Estados-Membros. Em matéria matrimonial, as novas definições incidem apenas sobre as normas de reconhecimento, pelo que serão abordadas /infra/ em IV.

Merece uma nota o artigo 2.º, n.º 3, do Regulamento Bruxelas II /ter/, que introduz uma novidade /ao nível da técnica legislativa/, ainda que não de substância. Neste preceito estabelece-se que para efeitos dos artigos 3.º, 6.º, 10.º, 12.º, 13.º, 51.º, 59.º, 75.º, 94.º e 102.º o conceito de «domicílio» substitui o conceito de «nacionalidade» para a Irlanda e o Reino Unido e tem o mesmo significado que nos respetivos ordenamentos jurídicos desses Estados-Membros[cite:Sobre este conceito, cf., com maiores detalhes;@almeida2017 pp. 142 e ss. e bibliografia aí indicada.]. Trata-se de uma concessão efetuada a estes Estados-Membros que constava já dos intrumentos precedentes. No Regulamento Bruxelas II /ter/ verifica-se uma alteração de técnica legislativa: ao invés de prever a substituição em cada um dos artigos em que ela é necessária, efetua-se a mesma numa única disposição que indica os artigos em que a substituição deve ocorrer. Atualmente, a substituição releva apenas para a Irlanda, pois o Reino Unido deixou, por via do /Brexit/, de ser um Estado-Membro. Tal significa, desde logo, que a substituição deixa de ser necessária no artigo 102.º, uma vez que a Irlanda não é um ordenamento jurídico complexo. Não se vê, igualmente, que seja necessário efetuar qualquer substituição no artigo 94.º, uma vez que ele não se refere ao elemento de conexão nacionalidade, mas sim ao princípio da não discriminação em razão da nacionalidade. Os restantes artigos ou correspondem a anteriores preceitos que já previam a substituição em sede do Regulamento Bruxelas II /bis/[fn:9] ou a artigos novos que recorrem à nacionalidade[fn:10].

Da perspetiva dos tribunais portugueses a questão pode parecer irrelevante, pois não vão, por exemplo, aferir a sua competência internacional através do recurso ao conceito de "domicílio". Todavia a apreensão deste conceito pelos tribunais portugueses é relevante para efeitos do artigo 6.º do Regulamento Bruxelas II /ter/: se dois cônjuges têm "domicílio" na Irlanda, os tribunais portugueses não podem recorrer às normas atributivas de competência internacional de fonte interna, porque os tribunais de um outro Estado-Membro (Irlanda) são competentes segundo as regras do Regulamento[fn:11]; é igualmente vedado o recurso às normas atributivas de competência internacional de fonte interna nos casos em que o cônjuge requerido tenha "domicílio" na Irlanda[fn:12].

* III. Competência internacional
** A) Critérios de competência alternativos e extensão de competência para pedidos reconvencionais

O Regulamento Bruxelas II /ter/ prevê, como previa o Regulamento Bruxelas II /bis/, sete critérios alternativos gerais (art. 3.º), um critério alternativo adicional para os casos de conversão da separação em divórcio (art. 5.º) e estabelece que os tribunais internacionalmente competentes nos termos dos artigos 3.º e 5.º são igualmente competentes para conhecer eventual pedido reconvencional em matéria matrimonial (art. 4.º). Os critérios são alternativos no sentido em que são de aplicação concorrente[cite:Cf. @musseva2022, pp.30-31;@oliveira2022, p. 36;e, em sede de Regulamento Bruxelas II /bis/, @almeida2017, pp. 95-97 e indicações bibliográficas aí indicadas].

Os sete critérios alternativos gerais (art. 3.º) mantêm-se substancialmente inalterados, pois todas as alterações efetuadas são de cariz formal. Na alínea /a)/ substituem-se os travessões por subalíneas, relocaliza-se a substituição da nacionalidade pelo "domicílio", atualmente relevante apenas para a Irlanda, para as definições (art. 2.º, n.º 3)[fn:13] e ajusta-se a técnica legislativa destinada a assinalar a alternatividade dos critérios, passando-se a indicar a expressão "ou" apenas nas subalíneas v) e vi) da alínea /a)/ do artigo 3.º do Regulamento Bruxelas II /ter/.

Da perspetiva da ordem jurídica portuguesa este sete critérios alternativos gerais atribuem competência internacional atendendo à residência habitual de um ou de ambos os cônjuges e a à nacionalidade comum dos cônjuges. Mais do que efetuar uma análise detalhada de cada um destes sete critérios, parece-nos relevante dar conta da jurisprudência do TJ sobre estes critérios em sede do Regulamento Bruxelas II /bis/ e que se mantém plenamente aplicável no contexto do novo Regulamento Bruxelas II /ter/.

Em matéria de nacionalidade comum dos cônjuges, assinala-se o Acórdão /Hadadi/[fn:14]. O litígio em causa opunha um casal em que ambos tinham nacionalidade húngara e francesa. O tribunal de reenvio colocou ao TJ três questões prejudiciais em que, em síntese, perguntava como se deveria aplicar a norma atributiva de competência internacional assente na nacionalidade comum dos cônjuges quando estes tinham mais de uma nacionalidade comum: dando prevalência à nacionalidade do foro (questão 1), dando prevalência à nacionalidade mais efetiva (questão 2) ou admitindo que qualquer uma das nacionalidade comuns atribuía competência internacional aos tribunais desse Estado-Membro (questão 3).

O TJ respondeu negativamente às duas primeiras questões, perfilhando o entendimento descrito na terceira questão. A prevalência da nacionalidade do foro foi recusada por conduzir a interpretações diferentes do mesmo preceito do Regulamento Bruxelas II /bis/, o que é contrário à obrigação de interpretação autónoma e uniforme das disposições do Regulamento[fn:15]. O critério da nacionalidade mais efetiva foi afastado tendo em conta os objetivos e a construção das normas de competência internacional do Regulamento Bruxelas II /bis/. A adoção deste critério teria como efeito restringir o número de foros quando o Regulamento Bruxelas II /bis/ prossegue o /favor divortii/ (ou, de forma mais ampla, o favorecimento da dissolução do matrimónio) através da pluralidade de foros[fn:16]. É igualmente um critério de caráter pouco preciso[fn:17], quando o Regulamento privilegia um elemento de conexão unívoco e de fácil aplicação e a sua determinação faz-se, muitas vezes com recurso à residência habitual o que levaria a sobreposição dos critérios de competência internacional e até, em certa medida, à prevalência da residência habitual sobre a nacionalidade nos casos de plurinacionalidades comuns[fn:18].

No Acórdão /Hadadi/ o TJ estabeleceu o princípio de tratamento paritário das nacionalidades da União Europeia e concedeu ao cônjuge requerente o direito de optar por qualquer uma das nacionalidades comuns da União Europeia dos cônjuges[fn:19].

Os restantes (seis) critérios alternativos gerais assentam na residência habitual de um ou de ambos os cônjuges. O conceito de residência habitual não se encontra definido no Regulamento Bruxelas II /ter/ e, apesar de existir vasta jurisprudência sobre a residência habitual das crianças, só recentemente, em dois acórdãos, o TJ se pronunciou sobre o conceito de residência habitual dos cônjuges.

No Acórdão /IB contra FA/[fn:21], IB, nacional francês, casou com FA, nacional irlandesa, em 1994 e fixaram domicílio conjugal na Irlanda, em 1999. IB alegou, no processo judicial de divórcio por si intentado, que exerce desde 2010 a sua atividade profissional em França e de forma estável e permanente desde maio de 2017.

O órgão jurisdicional de reenvio considerou que IB tinha duas residências: uma familiar, na Irlanda, e uma profissional, na França e colocou a seguinte questão prejudicial:

#+begin_quote
«Quando […] resulte das circunstâncias de facto que um dos cônjuges divide a sua vida entre dois Estados-Membros, pode considerar-se, na aceção do artigo 3.º do Regulamento n.º 2201/2003 e para efeitos da sua aplicação, que esse cônjuge tem a sua residência habitual em dois Estados-Membros, de modo que, se os requisitos estabelecidos nesse artigo estiverem preenchidos relativamente a dois Estados-Membros, os tribunais desses dois Estados são igualmente competentes para decidir sobre o divórcio?»[fn:20]
#+end_quote

O TJ, interpretando autonomamente o conceito no contexto do Regulamento Bruxelas II /bis/, conclui que o cônjuge não pode ter, num dado momento, mais de uma residência habitual. Fundamenta a sua conclusão, essencialmente em três ordens de razão: (i) o conceito não é empregue na sua forma plural no Regulamento Bruxelas II /bis/[fn:22]; (ii) a ideia de centro de interesses não aponta no sentido de o conceito residência habitual poder suscitar problemas de conteúdo múltiplo, isto é, de permitir que, em simultâneo, uma pessoa tenha mais do que uma residência habitual[fn:23]; (iii) e os objetivos prosseguidos pelo Regulamento Bruxelas II /bis/ também apontam no mesmo sentido, pois admitir a possibilidade de um cônjuge ter mais de uma residência habitual em simultâneo acarretaria o risco de a competência internacional ser determinada, em última análise, não pelo critério da «residência habitual», mas por um critério baseado na simples residência de um ou de outro dos cônjuges, o que infringiria o Regulamento Bruxelas II /bis/[fn:24]. Risco que seria acrescido por outros regulamentos atribuírem competências noutras matérias, como obrigações alimentares ou regimes matrimoniais, ao tribunal internacionalmente competente para julgar a ação de divórcio, separação judicial ou anulação do casamento[fn:25].

De seguida, o TJ efetua algumas considerações sobre o conceito autónomo de residência habitual. Seguindo a sua anterior jurisprudência, assinala que o conceito reflete essencialmente uma questão de facto, devendo os tribunais atender a todas as circunstâncias de facto específicas do caso concreto[fn:26]. Assinala que as circunstâncias específicas que permitem determinar a residência habitual de crianças não são idênticas em todos os aspectos às que permitem determinar a residência habitual dos cônjuges[fn:27].

O TJ recorda que a interpretação do conceito autónomo de residência habitual se caracteriza, em princípio, por dois elementos: por um lado, a vontade do interessado de fixar o centro habitual dos seus interesses num determinado lugar, e, por outro, uma presença com um grau suficiente de estabilidade no território do Estado-Membro em causa[fn:28]. A esta luz, e para que seja possível recorrer aos critérios de competência previstos no artigo 3.º, n.º 1, al. /a)/, quinto e sexto travessões, do Regulamento Bruxelas II /bis/, o cônjuge requerente deve ter transferido a sua residência habitual para o território de um Estado-Membro diferente do da anterior residência habitual comum e, portanto, por um lado, ter manifestado a vontade de estabelecer o centro habitual dos seus interesses nesse outro Estado-Membro, e, por outro, ter demonstrado que a sua presença no território deste Estado-Membro revela um grau suficiente de estabilidade[fn:29]. No caso concreto, o TJ entendeu indicar que os elementos constantes dos autos parecem, /a priori/, permitir demontrar a transferência de residência, o carácter estável da mesma e, pelo menos, a integração do cônjuge requerente no ambiente social e cultural do Estado-Membro da nova residência[fn:30]; não deixou, porém, de assinalar que compete ao órgão jurisdicional de reenvio a concreta tarefa de verificar se houve ou não, no caso concreto, mudança da residência habitual do cônjuge requerente[fn:31].

No Acórdão /MPA/[fn:32], MPA, nacional espanhola, casou em agosto de 2010, na embaixada espanhola da Guiné-Bissau, com LCDNMT, nacional português. Têm dois filhos, nascidos em Espanha, nos anos de 2007 e 2012, ambos com dupla nacionalidade portuguesa e espanhola. Os cônjuges residiram na Guiné-Bissau entre agosto de 2010 e fevereiro de 2015. Depois disso passaram a residir no Togo. Separaram-se de facto em 2018, continuam ambos a morar no Togo. Ambos os cônjuges trabalham para a Comissão Europeia e estão afetos à delegação da União no Togo. Têm a categoria profissional de agentes contratuais[fn:33]. MPA apresentou, junto dos tribunais espanhois, um pedido de divórcio, acompanhado de pedidos relativos à determinação do regime e das modalidades de exercício da guarda e das responsabilidade parentais em relação aos filhos menores do casal, à pensão de alimentos para estes últimos, bem como ao uso da casa de morada de família situada no Togo[fn:34].

Após decisão do tribunal espanhol de primeira instância, que se declarou incompetente por nenhum dos cônjuges ter residência habitual na Espanha, e interposição de recurso da decisão por parte da MPA, o órgão jurisdicional de reenvio decidiu suspender a instância e colocar várias questões prejudiciais ao TJ tendo as duas que transcrevemos particular relevância para o nosso estudo:

#+begin_quote
   1) Como deve ser interpretado o conceito de “residência habitual” do artigo 3.º do Regulamento n.º 2201/2003 e do artigo 3.º do Regulamento n.º 4/2009 dos nacionais de um Estado-Membro que residem num Estado terceiro devido às funções que lhes são confiadas enquanto agentes contratuais da [União] e que, no Estado terceiro, têm a qualidade de agentes diplomáticos da [União], quando a sua permanência, nesse Estado, esteja ligada ao exercício das funções que exercem para a União?

(...)

   4) No caso de se demonstrar que a residência habitual dos progenitores e dos menores não se situa num Estado-Membro, tendo em conta que, em conformidade com o Regulamento n.º 2201/2003, não existe nenhum outro Estado-Membro competente para conhecer dos pedidos, o facto de o requerido ser nacional de um Estado-Membro obsta à aplicação da cláusula residual prevista nos artigos 7.° e 14.° do Regulamento n.º 2201/2003?[fn:35]
#+end_quote

Por agora focar-nos-emos apenas na resposta do TJ à primeira questão. A resposta à outra questão será abordada /infra/ aquando da análise do critério de competência residual.


** B) Critério de competência residual
** C) Controlo da competência
** D) Controlo da citação
** E) Litispendência e ações dependentes

* IV. Reconhecimento
* V. Conclusões

* Footnotes
[fn:35]Acórdão de 1 de agosto de 2022, /MPA/, C-501/20, EU:C:2022:619, considerando 37.

[fn:34] Acórdão de 1 de agosto de 2022, /MPA/, C-501/20, EU:C:2022:619, considerando 30.

[fn:33] Acórdão de 1 de agosto de 2022, /MPA/, C-501/20, EU:C:2022:619, considerandos 27 a 29.

[fn:32] Acórdão de 1 de agosto de 2022, /MPA/, C-501/20, EU:C:2022:619.

[fn:31] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 61.

[fn:30] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos 59 e 60.

[fn:29] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 58.

[fn:28] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 57.

[fn:27] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos 53 e 54.

[fn:26] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 52.

[fn:25] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 48.

[fn:24] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 46.

[fn:23] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos 41 e 43.

[fn:22] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 40.

[fn:21] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955.

[fn:20] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando 23.

[fn:19] Pensa-se que do Acórdão /Hadadi/ se pode inferir a solução para dois casos próximos: tendo os cônjuges duas ou mais nacionalidades comuns, sendo apenas uma de um Estado-Membro da União Europeia, o cônjuge requerente pode intentar a ação matrimonial nos tribunais desse Estado-Membro, mesmo que essa não seja a nacionalidade mais efetiva; se apenas um dos cônjuges for plurinacional e a nacionalidade comum não for a sua nacionalidade efetiva (v.g. A., nacional português e italiano, é casado com B., nacional italiana e residem habitualmente em Portugal), ainda assim os cônjuges têm uma nacionalidade comum (no exemplo, a nacionalidade italiana) e qualquer um deles pode intentar a ação matrimonial juntos dos tribunais italianos.

[fn:18] Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, EU:C:2009:474, considerandos n.º 54.

[fn:17] Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, EU:C:2009:474, considerandos n.ºs 51 e 55.

[fn:16] Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, EU:C:2009:474, considerandos n.ºs 49, 52 e 53.

[fn:15] Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, EU:C:2009:474, considerandos n.ºs 37 a 41.

[fn:14] Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, EU:C:2009:474.

[fn:13] O que permitiu suprimir o n.º 2 do artigo 3.º do Regulamento Bruxelas II /bis/ e a parte final do 6.º travessão da alínea /a)/ do mesmo preceito, atual artigo 3.º, alínea /a)/, subalínea vi), do Regulamento Bruxelas II /ter/.

[fn:12] Cf. artigo 2.º, n.º 3, e 6.º, n.º 2, do Regulamento Bruxelas II /ter/.

[fn:11] Os artigos 2.º, n.º 3, e 3.º, alínea /b)/, do Regulamento Bruxelas II /ter/ conferem competência internacional aos tribunais da Irlanda. O artigo 6.º, n.º 1, impede o recurso às normas de competência internacional de fonte interna.

[fn:10] Artigos 10.º, 12.º, 13.º, 51.º e 59.º.

[fn:9] Artigos 3.º, 6.º e 75.º.

[fn:8] A questão surgiu, inicialmente, com a interpretação dos conceitos da Convenção de Bruxelas de 1968 relativa à Competência Jurisdicional e à Execução de Decisões em Matéria Civil e Comercial, com maior acuidade no Acórdão de 14 de outubro de 1976, /Eurocontrol/, 29/76, EU:C:1976:137, considerando n.º 3. No âmbito do Regulamento Bruxelas II /bis/, veja-se, por exemplo, o Acórdão de 2 de abril de 2009, /A./, C-523/07, EU:C:2009:225, considerando n.º 34, e os recentes Acórdãos de 2 de agosto de 2021, /A. contra B./, proc. C-262/21 PPU, EU:C:2021:640, considerando n.º 40 e de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos n.º 38 e ss..

[fn:7] Cf. artigos 64.º e ss. do Regulamento Bruxelas II /ter/.

[fn:6] Cf. Anexo I do Regulamento Bruxelas II /bis/.

[fn:5] Cf. ponto 5.1 do Anexo II e ponto 6.1 do Anexo VII do Regulamento Bruxelas II /ter/.

[fn:4] O âmbito de aplicação em razão do tempo deve, assim, ser também articulado com a norma revogatória prevista no artigo 104.º do Regulamento Bruxelas II /ter/. Apesar de o Regulamento Bruxelas II /ter/ revogar o Regulamento Bruxelas II /bis/ com efeitos a partir de 1 de agosto de 2022 (artigo 104.º, n.º 1), as normas deste último Regulamento continuam a aplicar-se sempre que a ação tenha sido instaurada, o ato autêntico exarado e o acordo registado antes de 1 de agosto de 2022.

[fn:3] A data de produção de efeitos destes três artigos coincide com a data de entrada em vigor. Tal justifica-se por razões diversas: os artigos 92.º e 93.º atribuem à Comissão Europeia o poder de adotar atos delegados no que respeita aos anexos do Regulamento, podendo haver interesse em que a Comissão Europeia possa exercer este poder ainda antes da data de aplicação do Regulamento; o artigo 103.º estabelece obrigações de informação aos Estados-Membros, relacionadas com a operacionalização do Regulamento, que deveriam ser comunicadas à Comissão Europeia até 23 de abril de 2021.

[fn:2] Regulamento (CE) n.º 2201/2003 do Conselho, de 27 de Novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.º 1347/2000, publicado no JO L 338, de 23 de dezembro de 2003.

[fn:1] Regulamento (UE) 2019/1111 do Conselho, de 25 de junho de 2019, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e ao rapto internacional de crianças (reformulação), publicado no Jornal Oficial (JO) L 178, de 2 de julho de 2019.
